config/routes.rb
Ellen::Application.routes.draw do
  devise_for :admins

  root :to => 'pages#index'

  resources :tickets
  resources :status_changes
  resources :users
  resources :trackings

  match 'login' => 'users#login'
  match 'logout' => 'pages#show_login'
  match 'update_tracking' => 'users#update_tracking'
  match 'unsubscribe' => 'pages#unsubscribe'

end

app/models/status_change.rb
class StatusChange < ActiveRecord::Base
  attr_accessible :from_status, :to_status, :ticket_id
  belongs_to :ticket
end

app/controllers/status_changes_controller.rb
class StatusChangesController < ApplicationController
  before_filter :check_admin

  # GET /status_changes
  # GET /status_changes.json
  def index
    @status_changes = StatusChange.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @status_changes }
    end
  end

  # GET /status_changes/1
  # GET /status_changes/1.json
  def show
    @status_change = StatusChange.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status_change }
    end
  end

  # GET /status_changes/new
  # GET /status_changes/new.json
  def new
    @status_change = StatusChange.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status_change }
    end
  end

  # GET /status_changes/1/edit
  def edit
    @status_change = StatusChange.find(params[:id])
  end

  # POST /status_changes
  # POST /status_changes.json
  def create
    @status_change = StatusChange.new(params[:status_change])

    respond_to do |format|
      if @status_change.save
        format.html { redirect_to @status_change, notice: 'Status change was successfully created.' }
        format.json { render json: @status_change, status: :created, location: @status_change }
      else
        format.html { render action: "new" }
        format.json { render json: @status_change.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /status_changes/1
  # PUT /status_changes/1.json
  def update
    @status_change = StatusChange.find(params[:id])

    respond_to do |format|
      if @status_change.update_attributes(params[:status_change])
        format.html { redirect_to @status_change, notice: 'Status change was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status_change.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_changes/1
  # DELETE /status_changes/1.json
  def destroy
    @status_change = StatusChange.find(params[:id])
    @status_change.destroy

    respond_to do |format|
      format.html { redirect_to status_changes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/status_changes_helper.rb
module StatusChangesHelper
end

app/views/status_changes/_form.html.erb
<%= form_for @status_change, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :from_status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :from_status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :to_status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to_status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ticket_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :ticket_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                status_changes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/status_changes/edit.html.erb
<%- model_class = StatusChange -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/status_changes/index.html.erb
<%- model_class = StatusChange -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:from_status) %></th>
      <th><%= model_class.human_attribute_name(:to_status) %></th>
      <th><%= model_class.human_attribute_name(:ticket_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @status_changes.each do |status_change| %>
      <tr>
        <td><%= link_to status_change.id, status_change_path(status_change) %></td>
        <td><%= status_change.from_status %></td>
        <td><%= status_change.to_status %></td>
        <td><%= status_change.ticket_id %></td>
        <td><%=l status_change.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_status_change_path(status_change), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      status_change_path(status_change),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_status_change_path,
            :class => 'btn btn-primary' %>

app/views/status_changes/new.html.erb
<%- model_class = StatusChange -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/status_changes/show.html.erb
<%- model_class = StatusChange -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:from_status) %>:</strong></dt>
  <dd><%= @status_change.from_status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:to_status) %>:</strong></dt>
  <dd><%= @status_change.to_status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ticket_id) %>:</strong></dt>
  <dd><%= @status_change.ticket_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              status_changes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_status_change_path(@status_change), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              status_change_path(@status_change),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>