config/routes.rb
Ellen::Application.routes.draw do
  devise_for :admins

  root :to => 'pages#index'

  resources :tickets
  resources :status_changes
  resources :users
  resources :trackings

  match 'login' => 'users#login'
  match 'logout' => 'pages#show_login'
  match 'update_tracking' => 'users#update_tracking'
  match 'unsubscribe' => 'pages#unsubscribe'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Ellen DeGeneres Show Ticket Tracker</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>

    <!-- Javascripts
    ================================================== -->
    <%= javascript_include_tag "application" %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
    
    <!-- Google Analytics -->
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-20298082-4']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    
  </head>
  <body>
    <header>
      <div class="container-fluid">
      <div class="row-fluid">
      <div class="span10 offset1">
        <h1 id="logotext"><%= link_to "The Ellen DeGeneres Show Ticket Tracker", root_url %></h1>
          <% if admin_signed_in? %>
          <%= link_to('Users', users_path) %>
          <%= link_to('Trackings', trackings_path) %>
          <%= link_to('Tickets', tickets_path) %>
          <%= link_to('Status Changes', status_changes_path) %>
          <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
          <% end %>
      </div>
      </div>
    </header>
    
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->



  </body>
</html>