config/routes.rb
Ellen::Application.routes.draw do
  devise_for :admins

  root :to => 'pages#index'

  resources :tickets
  resources :status_changes
  resources :users
  resources :trackings

  match 'login' => 'users#login'
  match 'logout' => 'pages#show_login'
  match 'update_tracking' => 'users#update_tracking'
  match 'unsubscribe' => 'pages#unsubscribe'

end

app/models/tracking.rb
class Tracking < ActiveRecord::Base
  attr_accessible :date
  has_and_belongs_to_many :users
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  before_filter :check_admin
  
  # GET /trackings
  # GET /trackings.json
  def index
    @trackings = Tracking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trackings }
    end
  end

  # GET /trackings/1
  # GET /trackings/1.json
  def show
    @tracking = Tracking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tracking }
    end
  end

  # GET /trackings/new
  # GET /trackings/new.json
  def new
    @tracking = Tracking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tracking }
    end
  end

  # GET /trackings/1/edit
  def edit
    @tracking = Tracking.find(params[:id])
  end

  # POST /trackings
  # POST /trackings.json
  def create
    @tracking = Tracking.new(params[:tracking])

    respond_to do |format|
      if @tracking.save
        format.html { redirect_to @tracking, notice: 'Tracking was successfully created.' }
        format.json { render json: @tracking, status: :created, location: @tracking }
      else
        format.html { render action: "new" }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trackings/1
  # PUT /trackings/1.json
  def update
    @tracking = Tracking.find(params[:id])

    respond_to do |format|
      if @tracking.update_attributes(params[:tracking])
        format.html { redirect_to @tracking, notice: 'Tracking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackings/1
  # DELETE /trackings/1.json
  def destroy
    @tracking = Tracking.find(params[:id])
    @tracking.destroy

    respond_to do |format|
      format.html { redirect_to trackings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tracking_helper.rb
module TrackingHelper
end

app/helpers/trackings_helper.rb
module TrackingsHelper
end

app/views/trackings/_form.html.erb
<%= form_for @tracking, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date, :class => 'date_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                trackings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/trackings/edit.html.erb
<%- model_class = Tracking -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trackings/index.html.erb
<%- model_class = Tracking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @trackings.each do |tracking| %>
      <tr>
        <td><%= link_to tracking.id, tracking_path(tracking) %></td>
        <td><%= tracking.date %></td>
        <td><%=l tracking.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tracking_path(tracking), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tracking_path(tracking),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tracking_path,
            :class => 'btn btn-primary' %>

app/views/trackings/new.html.erb
<%- model_class = Tracking -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trackings/show.html.erb
<%- model_class = Tracking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @tracking.date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              trackings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tracking_path(@tracking), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tracking_path(@tracking),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>